# 🔥 IMPORTANT
baseurl = "https://0xashh.github.io/"
languageCode = "en-us"
title = "0xAsh"

# اللغة
defaultContentLanguage = "en"
hasCJKLanguage = false

# التعليقات (مش مستخدم حالياً)
disqusShortname = ""

# عدد البوستات بالصفحة
[pagination]
    pagerSize = 5

# معلومات الموقع
[params]
    mainSections = ["post"]

# Sidebar (مثل الصورة 🔥)
[params.sidebar]
    subtitle = "Binary Exploitation & Security Research"
    avatar = "img/avatar.png"

# روابط السوشال (اختياري)
[[params.social]]
name = "GitHub"
url = "https://github.com/0xAshh"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/"

# Menu (القائمة الجانبية)
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writeups"
url = "/post/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3
